### ISSUE TITLE
What is MageStack_Varnish_Model_Processor class used for?

### ISSUE THREAD

**Issue by raivis-vitols** [sonassi/magento-varnish#1]
Hi!

Looking through the module code I came across this class MageStack_Varnish_Model_Processor (in https://github.com/sonassi/magestack-varnish/blob/master/app/code/community/MageStack/Varnish/Model/Processor.php). And am now trying to figure out how it is used and why. 

1) Based on config.xml file contents, this is not a class rewrite - there are no rewrite configs present. Were they supposed to be there?

2) That is a cache processor, so can be configured for use in app/etc/enterprise.xml for Magento EE. By default it is Enterprise_PageCache_Model_Processor - the class MageStack_Varnish_Model_Processor extends. Is it required to change processor to MageStack_Varnish_Model_Processor in app/etc/enterprise.xml file?

3) It is just some leftover code and I should not stress about it. Or should I?

Thanks! Looking forward to hear from you!

**Comment by blessani** [comment]
Hi Ravis,

This was implemented for a single customer I believe, but I think it was for a specific use case. It shouldn't be required as a rule, so I've removed it from the repo in the latest version in master.

**Comment by raivis-vitols** [comment]
Great! Thank you!
